---
title: "Enrichment Analysis"
subtitle: "211130_Q96K97del_A603fs dataset"
author: "Lachlan Baer"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    fig_width: 8
    fig_height: 6
    fig_align: "center"
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  error = FALSE,
  fig.align = "center"
)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

# Main - goseq DAR vs Length

```{r}
top_terms_len <- goseq_len_res %>%
  dplyr::filter(sig) %>%
  pull(term)
top_terms_dar <- goseq_dar_res %>%
  dplyr::filter(sig) %>%
  pull(term)
plot_terms <- rev(unique(c(top_terms_len, top_terms_dar)))
goseq_len_res %>%
  dplyr::select(term, len_p = p, len_fdr = fdr, len_sig = sig) %>%
  left_join(goseq_dar_res) %>%
  dplyr::select(
    term, len_p, len_sig, len_fdr,
    dar_p = p, dar_fdr = fdr, dar_sig = sig
  ) %>%
  dplyr::filter(term %in% plot_terms) %>%
  pivot_longer(cols = c("len_p", "dar_p"), names_to = "p_group", values_to = "p") %>%
  mutate(
    p_group = factor(p_group, levels = c("dar_p", "len_p")),
    term = factor(term, levels = plot_terms),
    labs = case_when(
      p_group == "len_p" & len_sig ~ "*",
      p_group == "len_p" & !len_sig ~ "",
      p_group == "dar_p" & dar_sig ~ "*",
      p_group == "dar_p" & !dar_sig ~ "",
    )
  ) %>%
  ggplot(aes(term, -log10(p), group = p_group, fill = p_group)) +
  geom_bar(stat = "identity", position = "dodge", colour = "black") +
  geom_text(
    aes(term, -log10(p) + 0.1, group = p_group, label = labs),
    position = position_dodge2(width = 0.9, padding = 0.2),
    size = 5,
    vjust = 0.77
  ) +
  coord_flip() +
  scale_fill_manual(
    limits = c("len_p", "dar_p"),
    values = c("#88CCEE", "#CC6677"),
    labels = c("Transcript length", "DAR")
  ) +
  scale_y_continuous(breaks = seq(0, 6, 1)) +
  labs(x = "GO term", y = log10plab, fill = "Bias data")
```

```{r}
ggsave(
  "~/phd/publications/fisher_pub/figures/main/goseq.png",
  device = "png",
  width = 18,
  height = 5,
  units = "cm"
)
```

# Supp - DAR PWF

```{r}
## Modified this code from goseq plotPWF function so I can use ggplot instead
pwf <- pwf_dar
w <- !is.na(pwf$bias.data)
o <- order(pwf$bias.data[w])
rang <- max(pwf$pwf, na.rm = TRUE) - min(pwf$pwf, na.rm = TRUE)
binsize <- 200
splitter <- ceiling(1:length(pwf$DEgenes[w][o])/binsize)
de <- sapply(split(pwf$DEgenes[w][o], splitter), mean)
binlen <- sapply(split(as.numeric(pwf$bias.data[w][o]), splitter), mean)

tibble(bias = binlen, de = de) %>%
  ggplot(aes(bias, de)) +
  geom_point(
    shape = 21,
    colour = "black",
    fill = alpha("black", 0.3),
    size = 2
  ) +
  geom_line(
    data = pwf,
    aes(x = bias.data, y = pwf),
    colour = 3
  ) +
  scale_x_continuous(breaks = seq(0, 0.8, 0.2)) +
  scale_y_continuous(breaks = seq(0, 0.2, 0.05)) +
  coord_cartesian(xlim = c(0, 0.8), ylim = c(0, 0.2)) +
  labs(
    x = "Mean DAR (200 gene bins)",
    y = "Proportion DE"
  )
```

```{r}
ggsave(
  "~/phd/publications/fisher_pub/figures/supp/pwf_dar.png",
  device = "png",
  width = 18,
  height = 12,
  units = "cm"
)
```

# Supp - Length PWF

```{r}
## Modified this code from goseq plotPWF function so I can use ggplot instead
pwf <- pwf_len
w <- !is.na(pwf$bias.data)
o <- order(pwf$bias.data[w])
rang <- max(pwf$pwf, na.rm = TRUE) - min(pwf$pwf, na.rm = TRUE)
binsize <- 200
splitter <- ceiling(1:length(pwf$DEgenes[w][o])/binsize)
de <- sapply(split(pwf$DEgenes[w][o], splitter), mean)
binlen <- sapply(split(as.numeric(pwf$bias.data[w][o]), splitter), mean)

tibble(bias = binlen, de = de) %>%
  ggplot(aes(bias, de)) +
  geom_point(
    shape = 21,
    colour = "black",
    fill = alpha("black", 0.3),
    size = 2
  ) +
  geom_line(
    data = pwf,
    aes(x = bias.data, y = pwf),
    colour = 3
  ) +
  coord_cartesian(xlim = c(0, 10000)) +
  labs(
    x = "Mean Length (200 gene bins)",
    y = "Proportion DE"
  )
```

```{r}
ggsave(
  "~/phd/publications/fisher_pub/figures/supp/pwf_len.png",
  device = "png",
  width = 18,
  height = 12,
  units = "cm"
)
```
