samples_tsv:

fastq_ext: ".fastq.gz"

pair_tags: ["_R1_001", "_R2_001"]

ref:
  species: "danio_rerio"
  assembly: "GRCz11"
  ensembl_release: 101

align:
  read_length: 100

umi:
  activate: True
  add_header:
    activate: False
    tag:

merge_samples:
  activate: True
  tags: ["_S1_1", "_S1_2", "_S1_3", "_S1_4"]

bootstrap_known_variants:
  activate: False

ase_counts:
  activate: True