samples_tsv: "config/samples.tsv"

fastq_ext: ".fastq.gz"

paired_end:
  activate: True
  tags: ["_R1_001", "_R2_001"]

merge_fastq:
  activate: True
  tags: ["_S1_1", "_S1_2", "_S1_3", "_S1_4"]

ref:
  species: "danio_rerio"
  assembly: "GRCz11"
  ensembl_release: 101

trim:
  phred_qual: 20
  length: 35
  extra: ""

align:
  read_length: 100
  extra: ""

count:
  min_qual: 1
  strandedness: 0
  min_overlap: 35
  frac_overlap: 0.9
  extra: ""